### ISSUE TITLE
Missing themes for 3DS, WiiU, Last Played, All Games and Favorites

### ISSUE THREAD

**Issue by wtstreetglow** [raelgc/es-theme-tronkyfran-super#2]
Is there any chance you could add the Wii U to yours as well as the 3Ds. The orginal tronkyfran has the Wii U. So maybe this is something I can fix on my own (just copy his Wii U folder to my directory but leave all of yours for the rest?-- I don't know, maybe that's not a good idea.)

And then one other thing I noticed is that all of the list like "last played", "all games", have went to a black background. I'm not sure why.

Thank you for any guidance or thoughts you can give on the situations above.

By the way, the additions you made look amazing!! So talented!!

**Comment by wtstreetglow** [comment]
I have fixed wii u by moving the original tronkyfran files to within your folder, I have also fixed, "last played", "all games", and "favorites" by the same method.

This only leaves fixing Nintendo 3ds (I didn't see a 3ds folder in your repo), the "RetroBat", "Final Burn", and "Windows" systems. Do you have any advice for me on those?

I thought about using the same concept. Copy paste from a repo that I like their design. (I got lucky between you helping me and the original tronky fran that these are all I have left)-- The sad thing I believe is they are going to look different because I don't have your or the orginal developers talent to make these.

Thank you for leading me to your repo for some additional fixes to my retro gaming setup. And thank you for any advice/ guidance you can give me on the above situation!!

**Comment by raelgc** [comment]
Right, thanks for mention all the missing entries. I'll start copying the WiiU, then later I'll see if I can create a art for 3DS.

In the past, I've made the ones for SegaCD, Saturn, Wii and PS3.

**Comment by wtstreetglow** [comment]
@raelgc Well I just found out the hard way, I didn't fix things as easily as I thought I did. :-( . All of my title screens looked great and now I realize when I go a level deeper into the actual game list for each of the new "systems" I made, they look nothing like yours for some reason. They are very ugly. Black background, blue text and nothing like your game list. And sadly I know nothing about what I'm doing. haha. Is there somewhere that you could give me some guidance on correcting the mess I've made if I can get the file structure to you? Essentially what I did is copy the mame directory and tried to use it's concepts for all of the missing systems. It looks like everything worked properly for the title screen but when you go one level deep, It's horrible. :-( . Yeah, you've done a great job, I have no clue how you do it, but it's polished for sure.

**Comment by wtstreetglow** [comment]
This looks great

![image](https://github.com/raelgc/es-theme-tronkyfran-super/assets/30456018/e6fb9799-4261-4ae1-b222-fbe0501aece1)

**Comment by wtstreetglow** [comment]
But I don't know why this did this
![image](https://github.com/raelgc/es-theme-tronkyfran-super/assets/30456018/7ecb233d-6ce2-4c6c-ad8a-9b7a9ce1e97c)

**Comment by wtstreetglow** [comment]
`<theme>
    <formatVersion>3</formatVersion>
    <include>./../simple.xml</include>

	<view name="system">

		<image name="background" extra="true">
			<path>./art/system.jpg</path>
		</image>

		<image name="logo">
			<path>./art/menu.png</path>
        </image>
		
		<helpsystem name="help">
			<textColor>ffffff88</textColor>
			<iconColor>ffffff88</iconColor>
		</helpsystem>
		
	</view>

	<view name="basic, detailed, video">
	
		<text name="system_name_1" extra="true">
			<text>LightGun</text>
			<forceUppercase>1</forceUppercase>
			<size>0.45 0.16</size>
			<pos>0.527 0</pos>
			<color>7b7d7f</color>
			<fontPath>./../art/OPENSANS-LIGHT.TTF</fontPath>
			<fontSize>0.055</fontSize>
			<alignment>right</alignment>
		</text>

		<image name="logo">
			<path>./art/system.jpg</path>
			<pos>0.025 0.079</pos>
			<maxSize>0.45 0.1</maxSize>
			<origin>0 0.5</origin>
		</image>

	</view>

	<view name="basic">
	
		<textlist name="gamelist">
			<pos>0.025 0.22</pos>
			<size>0.950 0.68</size>
			<alignment>center</alignment>
			<horizontalMargin>0.01</horizontalMargin>
		</textlist>
		
	</view>

	<view name="detailed">
	


		<image name="md_image">
			<pos>0.025 0.22</pos>
			<maxSize>0.18 0.301</maxSize>
			<origin>0 0</origin>
		</image>
		
		<text name="md_lbl_rating">
			<pos>0.232 0.21</pos>
		</text>
		
		<text name="md_lbl_releasedate">
			<pos>0.232 0.25</pos>
		</text>
		
		<text name="md_lbl_developer">
			<pos>0.232 0.29</pos>
			<size>0.133 0.04</size>
		</text>

		<text name="md_lbl_publisher">
			<pos>0.232 0.33</pos>
			<size>0.133 0.04</size>
		</text>
		
		<text name="md_lbl_genre">
			<pos>0.232 0.37</pos>
		</text>
		
		<text name="md_lbl_players">
			<pos>0.232 0.41</pos>
		</text>

		<text name="md_lbl_lastplayed">
			<pos>0.232 0.45</pos>
		</text>

		<text name="md_lbl_playcount">
			<pos>0.232 0.49</pos>
		</text>
		
		<text name="md_playcount">
			<pos>0.365 0.49</pos>
		</text>

		<datetime name="md_lastplayed">
			<pos>0.365 0.45</pos>
		</datetime>
		
		<text name="md_players">
			<pos>0.365 0.41</pos>
		</text>
		
		<text name="md_genre">
			<pos>0.365 0.37</pos>
			<size>0.17 0.04</size>
		</text>

		<text name="md_publisher">
			<pos>0.365 0.33</pos>
			<size>0.17 0.04</size>
		</text>
		
		<text name="md_developer">
			<pos>0.365 0.29</pos>
			<size>0.17 0.04</size>
		</text>
		
		<datetime name="md_releasedate">
			<pos>0.365 0.25</pos>
		</datetime>
		
		<rating name="md_rating">
			<pos>0.365 0.216</pos>
			<size>0.028 0.028</size>
			<filledPath>./../art/star_filled_spacing.svg</filledPath>
			<unfilledPath>./../art/star_hollow_3_spacing.svg</unfilledPath>
		</rating>
		
		<text name="md_description">
			<size>0.52 0.3</size>
			<pos>0.025 0.577</pos>
		</text>
		
		<textlist name="gamelist">
			<pos>0.615 0.22</pos>
			<size>0.359 0.68</size>
			<alignment>left</alignment>
			<horizontalMargin>0.01</horizontalMargin>
		</textlist>

	</view>
	
</theme>
`

**Comment by wtstreetglow** [comment]
`
<theme>`
`
    <formatVersion>3</formatVersion>`
`
    <include>./../simple.xml</include>
`
`
	<view name="system">
`
`


		<image name="background" extra="true">
			<path>./art/system.jpg</path>
		</image>

		<image name="logo">
			<path>./art/menu.png</path>
        </image>
		
		<helpsystem name="help">
			<textColor>ffffff88</textColor>
			<iconColor>ffffff88</iconColor>
		</helpsystem>
		
	</view>

	<view name="basic, detailed, video">
	
		<text name="system_name_1" extra="true">
			<text>LightGun</text>
			<forceUppercase>1</forceUppercase>
			<size>0.45 0.16</size>
			<pos>0.527 0</pos>
			<color>7b7d7f</color>
			<fontPath>./../art/OPENSANS-LIGHT.TTF</fontPath>
			<fontSize>0.055</fontSize>
			<alignment>right</alignment>
		</text>

		<image name="logo">
			<path>./art/system.jpg</path>
			<pos>0.025 0.079</pos>
			<maxSize>0.45 0.1</maxSize>
			<origin>0 0.5</origin>
		</image>

	</view>

	<view name="basic">
	
		<textlist name="gamelist">
			<pos>0.025 0.22</pos>
			<size>0.950 0.68</size>
			<alignment>center</alignment>
			<horizontalMargin>0.01</horizontalMargin>
		</textlist>
		
	</view>

	<view name="detailed">
	


		<image name="md_image">
			<pos>0.025 0.22</pos>
			<maxSize>0.18 0.301</maxSize>
			<origin>0 0</origin>
		</image>
		
		<text name="md_lbl_rating">
			<pos>0.232 0.21</pos>
		</text>
		
		<text name="md_lbl_releasedate">
			<pos>0.232 0.25</pos>
		</text>
		
		<text name="md_lbl_developer">
			<pos>0.232 0.29</pos>
			<size>0.133 0.04</size>
		</text>

		<text name="md_lbl_publisher">
			<pos>0.232 0.33</pos>
			<size>0.133 0.04</size>
		</text>
		
		<text name="md_lbl_genre">
			<pos>0.232 0.37</pos>
		</text>
		
		<text name="md_lbl_players">
			<pos>0.232 0.41</pos>
		</text>

		<text name="md_lbl_lastplayed">
			<pos>0.232 0.45</pos>
		</text>

		<text name="md_lbl_playcount">
			<pos>0.232 0.49</pos>
		</text>
		
		<text name="md_playcount">
			<pos>0.365 0.49</pos>
		</text>

		<datetime name="md_lastplayed">
			<pos>0.365 0.45</pos>
		</datetime>
		
		<text name="md_players">
			<pos>0.365 0.41</pos>
		</text>
		
		<text name="md_genre">
			<pos>0.365 0.37</pos>
			<size>0.17 0.04</size>
		</text>

		<text name="md_publisher">
			<pos>0.365 0.33</pos>
			<size>0.17 0.04</size>
		</text>
		
		<text name="md_developer">
			<pos>0.365 0.29</pos>
			<size>0.17 0.04</size>
		</text>
		
		<datetime name="md_releasedate">
			<pos>0.365 0.25</pos>
		</datetime>
		
		<rating name="md_rating">
			<pos>0.365 0.216</pos>
			<size>0.028 0.028</size>
			<filledPath>./../art/star_filled_spacing.svg</filledPath>
			<unfilledPath>./../art/star_hollow_3_spacing.svg</unfilledPath>
		</rating>
		
		<text name="md_description">
			<size>0.52 0.3</size>
			<pos>0.025 0.577</pos>
		</text>
		
		<textlist name="gamelist">
			<pos>0.615 0.22</pos>
			<size>0.359 0.68</size>
			<alignment>left</alignment>
			<horizontalMargin>0.01</horizontalMargin>
		</textlist>

	</view>
	
</theme>
`

**Comment by raelgc** [comment]
Ok, I've added themes for Xbox, 3DS, WiiU and Switch.

Now I'll take a look at "Last played", "All games", "Favorites" and "Light Gun".

**Comment by wtstreetglow** [comment]
Thank you so much!! You didn't have to do that but I am very appreciative of that!! I will give it a go shortly. Again thank you so much!!Sent from my iPhoneOn Dec 30, 2023, at 3:33 PM, Rael Gugelmin Cunha ***@***.***> wrote:﻿
Ok, I've added themes for Xbox, 3DS, WiiU and Switch.
Now I'll take a look at "Last played", "All games", "Favorites" and "Light Gun".

**Comment by raelgc** [comment]
Just added "Last played", "All games", "Favorites" and "Light Gun".

**Comment by wtstreetglow** [comment]
Thank you Rael!! Very thankful that you helped me with your talents!!So appreciative!!-WestonSent from my iPhoneOn Dec 31, 2023, at 7:48 AM, Rael Gugelmin Cunha ***@***.***> wrote:﻿
Closed #2 as completed.
